name: Deploy to Production
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
	@@ -19,4 +21,4 @@ jobs:
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 
          working-directory: ./
          alias-domains: | 
            test.prod.gauravjain98.com